version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
  app:
    build: .
    expose:
      - "8000"
    environment:
      - REDIS_HOST=redis
      - DB_URL=sqlite:///data/db.sqlite3
      - BASE_URL=https://certainty.dev
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    volumes:
      - ./data:/data
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rq_worker:
    build: .
    command: rq worker certainty
    environment:
      - REDIS_HOST=redis
      - DB_URL=sqlite:///data/db.sqlite3
      - BASE_URL=https://certainty.dev
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    volumes:
      - ./data:/data
    depends_on:
      - redis

  rq_scheduler:
    build: .
    command: rqscheduler --host redis --port 6379 --db 0 --interval 1
    environment:
      - REDIS_HOST=redis
      - DB_URL=sqlite:///data/db.sqlite3
      - BASE_URL=https://certainty.dev
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    volumes:
      - ./data:/data
    depends_on:
      - redis
